[workspace]
resolver = "3"
members = ["."]

[package]
name = "quick-noise"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
debug = "line-tables-only"
strip = false

[profile.bench]
opt-level = 3
debug = "line-tables-only"
strip = false

[dependencies]
num-traits = "0.2.19"
image = { version = "0.25.9", default-features = false, features = ["png"], optional = true }
paste = "1.0.15"
itertools = "0.14.0"
cfg-if = "1.0.4"

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support"] }
# fastnoise2 = "0.4.0"

[features]
image = ["dep:image"]

[[bench]]
name = "perlin"
harness = false

[[example]]
name = "basic"
required-features = ["image"]
